name         'bison-puppetmaster'
version      '0.0.1'
source       'git://github.com/bison/puppet-puppetmaster.git'
author       'Brad Ison'
license      'Apache License Version 2.0'
summary      'Puppet master Puppet module'
description  'This module helps with bootstrapping new puppet masters'
project_page 'https://github.com/bison/puppet-pupppetmaster'

dependency 'puppetlabs/stdlib', '>= 0.1.6'
dependency 'cprice404/inifile', '>= 0.9.0'
